import AppKit
import EventKit
import Foundation

@MainActor
private final class CountingCalendar: CalendarProviding {
    let fixture = DemoCalendarProvider()
    var access: CalendarAccess = .authorized
    var reads = 0
    var revision = 0
    func requestAccess() async throws -> Bool { true }
    func calendars() throws -> [CalendarDescriptor] { try fixture.calendars() }
    func events(calendarIDs: Set<String>, week: CalendarWeek) async throws -> [CalendarEventRecord] {
        reads += 1
        return try await fixture.events(calendarIDs: calendarIDs, week: week).map {
            var record = $0
            if revision > 0 { record.title = "Updated fixture \(revision)" }
            return record
        }
    }
}

@main
@MainActor
struct EnergyBehaviorVerification {
    static var count = 0
    struct Failure: Error, CustomStringConvertible { let description: String }
    static func expect(_ value: @autoclosure () -> Bool, _ message: String) throws {
        guard value() else { throw Failure(description: message) }
        count += 1
        print("PASS: \(message)")
    }
    static func settle(_ seconds: Double = 0.8) async throws {
        try await Task.sleep(for: .seconds(seconds))
    }
    static func main() async {
        do {
            guard CommandLine.arguments.contains("--automation-demo") else {
                throw Failure(description: "Only the explicit synthetic demo path is permitted")
            }
            let provider = CountingCalendar()
            let store = AppStore(calendarProvider: provider)
            try expect(store.isDemo, "Synthetic mode keeps personal settings and wallpaper untouched")
            store.automationSettings.refreshOnCalendarChange = true
            try await settle(1.5)
            try expect(provider.reads == 1 && store.entries.count == 5, "Initial enable fetches the fixture once")
            let before = provider.reads
            store.setStudioVisible(false)
            let hiddenPreview = store.preview
            for index in 1...10 {
                store.configuration.title = "Fictional design \(index)"
                try await settle(0.7)
            }
            try expect(provider.reads == before, "Ten settled appearance edits perform zero calendar reads")
            try expect(store.preview === hiddenPreview, "Hidden preview is not regenerated by design updates")
            for _ in 0..<10 {
                NotificationCenter.default.post(name: NSApplication.didBecomeActiveNotification, object: nil)
                try await settle(0.45)
            }
            try expect(provider.reads == before, "Ten ordinary activations perform zero calendar reads")
            NotificationCenter.default.post(name: NSApplication.didChangeScreenParametersNotification, object: nil)
            NotificationCenter.default.post(name: .NSCalendarDayChanged, object: nil)
            try await settle()
            try expect(provider.reads == before, "Same-day appearance and display notifications avoid calendar reads")
            provider.revision = 1
            for _ in 0..<20 { NotificationCenter.default.post(name: .EKEventStoreChanged, object: nil) }
            try await settle(0.1)
            store.configuration.title = "Latest simultaneous design"
            try await settle(1.5)
            try expect(provider.reads == before + 1, "A twenty-notification burst merged with an edit fetches once")
            try expect(store.entries.allSatisfy { $0.name == "Updated fixture 1" }, "An edit cannot consume the pending calendar change")
            try expect(store.configuration.title == "Latest simultaneous design", "Calendar catch-up keeps the newest design")
            try expect(store.preview === hiddenPreview, "Calendar changes apply without rendering a hidden preview")
            store.setStudioVisible(true)
            try expect(store.preview !== hiddenPreview, "Revealing the studio renders its latest state")
            let visiblePreview = store.preview
            store.refreshPreview()
            try expect(store.preview === visiblePreview, "Unchanged visible preview is reused")
            NSWorkspace.shared.notificationCenter.post(name: NSWorkspace.didWakeNotification, object: nil)
            try await settle(1.5)
            try expect(provider.reads == before + 2, "Real wake still performs conservative calendar catch-up")
            store.automationSettings.refreshOnCalendarChange = false
            try await settle()
            let disabledReads = provider.reads
            for _ in 0..<20 { NotificationCenter.default.post(name: .EKEventStoreChanged, object: nil) }
            try await settle(1.2)
            try expect(provider.reads == disabledReads, "Disabled automation ignores calendar notifications")
            try expect(StudioWindowLifecycle.permitsPreview(visible: true, miniaturized: false, occluded: false, appHidden: false), "A visible studio allows its preview even without keyboard focus")
            try expect(!StudioWindowLifecycle.permitsPreview(visible: false, miniaturized: false, occluded: false, appHidden: false), "A closed studio suppresses previews")
            try expect(!StudioWindowLifecycle.permitsPreview(visible: true, miniaturized: true, occluded: false, appHidden: false), "A minimized studio suppresses previews")
            try expect(!StudioWindowLifecycle.permitsPreview(visible: true, miniaturized: false, occluded: true, appHidden: false), "A fully occluded studio suppresses previews")
            try expect(!StudioWindowLifecycle.permitsPreview(visible: true, miniaturized: false, occluded: false, appHidden: true), "A hidden application suppresses previews")
            try expect(store.error == nil, "All scheduler interactions finish without errors")
            var oldConnection = store.calendarConnection!
            oldConnection.weekStart = CalendarWeek(containing: store.now.addingTimeInterval(-7 * 86400), timeZone: .current).start
            store.importCalendarEntries(store.entries, replace: true, subtitle: nil, connection: oldConnection)
            let beforeToggle = provider.reads
            store.automationSettings.refreshOnCalendarChange = true
            store.automationSettings.refreshWeekly = true
            try await settle(0.05)
            store.automationSettings.refreshWeekly = false
            try await settle(1)
            try expect(provider.reads == beforeToggle && store.calendarConnection?.weekStart == oldConnection.weekStart,
                       "Rapid weekly enable-disable revokes a debounced enable without advancing the retained week")
            store.automationSettings.refreshWeekly = true
            try await settle(1)
            let beforeOptOut = provider.reads
            provider.revision = 2
            NotificationCenter.default.post(name: .EKEventStoreChanged, object: nil)
            try await settle(0.1)
            store.automationSettings.refreshOnCalendarChange = false
            try await settle(1.2)
            try expect(provider.reads == beforeOptOut && store.entries.allSatisfy { $0.name == "Updated fixture 1" },
                       "Turning change sync off prunes a debounced calendar notification while weekly mode remains on")
            print("Verified \(count) energy and scheduler assertions using fictional fixtures only.")
        } catch {
            fputs("Energy behavior verification failed: \(error)\n", stderr)
            exit(1)
        }
    }
}
